### ISSUE TITLE
support targetting second LIVE option for Alpha 4.0

### ISSUE THREAD

**Issue by RGD2** [starcitizen-lug/lug-helper#100]
**Is your feature request related to a problem? Please describe.**
The install client fails to install 4.0 with an error code 2000

**Describe the solution you'd like**
The options for LIVE/PTU/EPTU expanded to include 4.0_PREVIEW

**Comment by myobfee** [comment]
I had the same issue and was able to resolve it by manually creating the 4.0_PREVIEW folder in the game directory. You should see folders for EPTU, LIVE, and PTU by default in that directory. Create another folder called 4.0_PREVIEW and the install will then start without error.

**Comment by mactan-sc** [comment]
if you are experiencing issues installing 4.0_PREVIEW including error code 2000 issues creating the directory, be sure to follow the [RSI Launcher2.0 migration guide](https://github.com/starcitizen-lug/knowledge-base/wiki/Tips-and-Tricks#rsi-launcher-20) detailed on the wiki.

issues with directory creation are due to powershell being missing from the wine prefix, use the lug helper maintenance section to add powershell

**Comment by the-sane** [comment]
Just to add further clarification: The option in the Helper to target a different version of the game is used for the Helper's functions like deleting shaders. It has no effect on installation of 4.0.

I'm closing this since there's no problem with the Helper. Following the instructions above and on our wiki will allow the launcher to update itself.

**Comment by RGD2** [comment]
Error 2000 is reputedly due to the lack of Powershell - for which there is now a maintenance option to add it to the prefix.
