### ISSUE TITLE
Pre-releases erroneously included in downloads list

### ISSUE THREAD

**Issue by snatella** [starcitizen-lug/lug-helper#23]
It's taken me so long to notice, but my 6.10 runners are listed alongside the 6.6 ones in the lug-helper - except the 6.10 ones are pre-release and not for general use.

Can we have pre-release runners marked as unstable or removed from the offerings? In this case 6.10 had the horrid wineserver cpu usage bug.

**Comment by snatella** [comment]
Looks like a

```
"prerelease": true,
```

Gets set, but filtering it out of the JSON without `jq` installed, that I'm less sure of.

**Comment by snatella** [comment]
After a bit of fiddling around, `"prerelease": false[^\[]+\[[^\]]+` will get you blocks of json without pre-releases in them

**Comment by the-sane** [comment]
I’ll take a look, thanks for pointing this out!

**Comment by the-sane** [comment]
Question:  What is your naming plan for actual releases?  Typically beta releases are named, ie, 6.10-beta1, 6.10-beta2, etc, but it looks like your pre-release is just 6.10 in the filename.  How will the final release be distinguished from betas?

Ideally, I would want the Helper to display "pre-release" by these downloads instead of just filtering them out.  If someone wants to download a beta to test it out, the Helper should oblige.  To do this is looking like a bit of work.  Not only is there the problem of parsing the json for that flag, but there might be filename conflicts too if you aren't using unique filenames for your betas.

Any parsing I do would also likely be github specific and wouldn't work on files hosted elsewhere.  It's looking like a lot of work at the moment.

**Comment by snatella** [comment]
Hey man, sorry I'm not sure where my github notifications go, but apparently nowhere useful. I've proposed removing my runners from the helper as it stands as the latest changes now break them anyway, and there are so many good options there's not much for me to add by getting my builds back in shape.

I'd probably do an alpha naming scheme in future to signify pre-release.
