### ISSUE TITLE
Runner name is not what Lutris Script expects

### ISSUE THREAD

**Issue by Azriel-Legnasia** [starcitizen-lug/lug-helper#26]
The default Lutris Script looks for "lutris-ge-6.21-1-x86_64" as it's runner, while the equivalent version you can get on the LUG Helper is "**_wine_**-lutris-ge-6.21-1-x86_64" which the script and thus Lutris thinks is a different runner entirely. This can, of course, easily be fixed by changing the name of the runner to the one that Lutris expects. I realize that this is technically a Scripting error made by whoever wrote the Lutris script, but I figured I'd post it here since a fix can in theory be made on this end.

As an aside, maybe have a little note on which runner version, etc the Lutris Script is expecting for install and request that it be installed first?

**Comment by the-sane** [comment]
Thanks for the report!  We're aware of this and have been in touch with the Lutris team to have it resolved on their end.  They've hardcoded the (wrong) filename into their script, which is causing a lot of people problems.  Since that file name doesn't actually exist on Glorious Eggroll's runner release page, the install fails.  Unfortunately, nobody in the LUG has access to make edits to the Lutris script, so we have to wait for them to fix it.

The Helper, on the other hand, pulls its list of runners directly from the github API, so the names you see in that list will always match the real file names as released by the runner maintainers.

As for a workaround, you have two options.  Either manually download and rename the runner, then place it in the download cache location you see in your terminal when Lutris would fail so that the install can continue, or edit the runner out of the Lutris install script entirely and use the Helper to install a real runner.

Hopefully the Lutris team fixes their script soon.
