### ISSUE TITLE
[NEW SCRIPT PROPOSAL] Script to increase performance for AMD THREADTHRIPPER

### ISSUE THREAD

**Issue by mrdev023** [starcitizen-lug/lug-helper#42]
I write a script to increase performance with my Threadthripper 2990WX. 
But i don't know how to integrated it because this script need to be run before and after playing at Star citizen.

Before

![before](https://user-images.githubusercontent.com/11292703/176961127-43bf82fb-1b58-4011-9b16-126b2c62dfb1.png)

After

![after](https://user-images.githubusercontent.com/11292703/176961141-3354a0b9-52e1-47cd-90c9-e08d7ad8b90d.png)

![Screenshot_20220630_195843](https://user-images.githubusercontent.com/11292703/176959350-6910483e-483c-40db-be37-5ed19fbf89b1.png)

https://gist.github.com/mrdev023/59f9ef9b40101745a645ce875697b79d

This script can work if each core is split to multiple PU.

```bash
lstopo # Show CPU topology 
```

Example of display:

![image](https://user-images.githubusercontent.com/11292703/176958345-1e0d8d71-ec02-40cb-9b42-891270f5243e.png)

Core L#0 is split in 2 Processing Unit, so if i disable the second PU for each Core. Star citizen performance is improved.

```bash
configure_sc.sh enable # To enable disable useless core
```

```bash
configure_sc.sh disable # To enable all cores
```

**Comment by the-sane** [comment]
Thanks for the contribution! Since this has to be run before and after playing, I’m not sure if the Helper is the right place for this script. It does, however, seem like a perfect candidate for that built-in script running option within Lutris. Once configured in the Lutris settings, Lutris will automatically handle running a pre/post script. 

I think we should add this script and the link to our wiki in the performance tuning page. If you open a ticket under the wiki’s project and copy/paste this info there, Beni can handle getting it into the right spot.

**Comment by mrdev023** [comment]
I recreate the same issue here https://github.com/starcitizen-lug/information-howtos/issues/6

**Comment by the-sane** [comment]
I gave Beni a heads up over there so he can take a look. I’ll close this, but maybe we’ll revisit it in the future as the Helper script continues to grow its functionality
