### ISSUE TITLE
Installation of Star Citizen Fails

### ISSUE THREAD

**Issue by TropicLegend** [starcitizen-lug/lug-helper#69]
**Describe the bug**
Star Citizen Launcher Install Fails
**To Reproduce**
1) Download LUG-Helper
2) Follow Wiki instructions until Installation Step 3
3) Step 3 of the Installation Steps from the Starcitizen-lug knowledge-base wiki.

**Expected behavior**
The Launcher should install

**Screenshots**
none needed

**OS Info:**
[System]
OS:              GNOME 45 Flatpak runtime [It's actually Fedora Kinoite - Ublue Image for Nvidia, I don't know why it says that]
Arch:            x86_64
Kernel:          6.5.7-200.fc38.x86_64
Desktop:         KDE
Display Server:  wayland

[CPU]
Vendor:          AuthenticAMD
Model:           AMD Ryzen 9 5900X 12-Core Processor
Physical cores:  12
Logical cores:   24

[Memory]
RAM:             31.3 GB
Swap:            8.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 4080/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 535.113.01
OpenGL Core:     4.6.0 NVIDIA 535.113.01
OpenGL ES:       OpenGL ES 3.2 NVIDIA 535.113.01
Vulkan Version:  1.3.261
Vulkan Drivers:  NVIDIA GeForce RTX 4080 (1.3.242)

**Additional context**
Logs: https://pastebin.com/9bfj9RqU

There was some pinned comment about this in the Linux Users Group Discord Server but it didn't help solving the problem.

**Comment by the-sane** [comment]
Hi! Lutris/winetricks is having some issues downloading these files lately and we're waiting on fixes or solutions from upstream. I see you've been in our Discord tech support channel. Best bet is to just hang out there for a while and someone will be able to help you work around this. We have folks from all different timezones in there so just be a bit patient.

I'm going to close this issue since it's nothing we can control on our end.
